#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a distro-specific bootstrap script, sourced from main.sh, and as such
# has access to all of the variables set by main.sh, namely $tmp (the temporary
# directory), $INSTALLERDIR/$DISTRO, $RELEASE, $BOOTSTRAP_RELEASE (if different
# from $RELEASE), $ARCH, and $MIRROR.

# get Docker build
echo
echo "Getting Docker build from Fedora Koji buildsystem..."
echo

wget $MIRROR -O "$tmp/docker-fedora.tar.xz"

cd $tmp

echo "Extracting the downloaded tarball..."
tar xf "$tmp/docker-fedora.tar.xz" --strip-components=1

# delete the remains
rm "$tmp/docker-fedora.tar.xz"
rm json
rm VERSION

cd - > /dev/null

echo "Extracting filesystem..."

mkdir -p "$tmp"/"$subdir"
cd "$tmp/$subdir"

tar xfp "$tmp"/layer.tar

echo "Extracting finished!"
cd - > /dev/null

#fixing groups and users
echo 'Fixing groups and users'

rm "$tmp/$subdir/etc/group"

cp $INSTALLERDIR/$DISTRO/group "$tmp/$subdir/etc/group"

rm "$tmp/$subdir/etc/gshadow"
cp $INSTALLERDIR/$DISTRO/gshadow "$tmp/$subdir/etc/gshadow"

rm "$tmp/$subdir/etc/shadow"
cp $INSTALLERDIR/$DISTRO/shadow "$tmp/$subdir/etc/shadow"

rm "$tmp/$subdir/etc/passwd"
cp $INSTALLERDIR/$DISTRO/passwd "$tmp/$subdir/etc/passwd"

# adding message for later
cp $INSTALLERDIR/$DISTRO/fedoralogo.txt "$tmp/$subdir/etc/.fedoracroutonmsg"
