#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a distro-specific bootstrap script, sourced from main.sh, and as such
# has access to all of the variables set by main.sh, namely $tmp (the temporary
# directory), $INSTALLERDIR/$DISTRO, $RELEASE, $BOOTSTRAP_RELEASE (if different
# from $RELEASE), $ARCH, and $MIRROR.

# get Docker build
echo
echo "Getting container build from Fedora official repositories..."
echo
echo $MIRROR
#if ! curl -N -f -L --connect-timeout 60 --retry 2 "$MIRROR" \
#        | tar -C "$tmp" --exclude json --exclude VERSION 2>&-; then
#    error 1 'Failed to download fedora.
#Check your internet connection or proxy settings and try again.'
#fi

cd $tmp

curl -N -f -L -# --connect-timeout 60 --retry 2 $MIRROR -O

echo "Extracting the downloaded tarball..."
tar xf *.tar.xz --strip-components=1 --exclude json --exclude VERSION

# delete the remains
rm *.tar.xz

cd - > /dev/null

echo "Extracting filesystem..."

mkdir -p "$tmp"/"$subdir"
cd "$tmp/$subdir"

tar xfp "$tmp"/layer.tar

echo "Extracting finished!"
cd - > /dev/null

#fixing groups and users
echo 'Fixing groups and users'

rm "$tmp/$subdir/etc/group"

cp $INSTALLERDIR/$DISTRO/group "$tmp/$subdir/etc/group"

rm "$tmp/$subdir/etc/gshadow"
cp $INSTALLERDIR/$DISTRO/gshadow "$tmp/$subdir/etc/gshadow"

rm "$tmp/$subdir/etc/shadow"
cp $INSTALLERDIR/$DISTRO/shadow "$tmp/$subdir/etc/shadow"

rm "$tmp/$subdir/etc/passwd"
cp $INSTALLERDIR/$DISTRO/passwd "$tmp/$subdir/etc/passwd"

# adding message for later
cp $INSTALLERDIR/$DISTRO/fedoralogo.txt "$tmp/$subdir/etc/.fedoracroutonmsg"
