#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m | sed -e 's i.86 i386 ;s arm.* armhfp ;'`"
fi

# Latest Koji builds are here:
# Find the one for your arch and substitute is below! Look for Fedora-Docker-Base
# http://koji.fedoraproject.org/koji/tasks?owner=ausil&state=closed&view=flat&method=createImage&order=-id
#
# For Fedora 24 look here:
# http://koji.fedoraproject.org/koji/tasks?owner=releng&state=all&view=flat&method=createImage&order=-id
#
# ARM images are available aswell as 32-bit images

if [ -z "$MIRROR" ]; then
    MIRROR="${CROUTON_MIRROR_fedora:-https://kojipkgs.fedoraproject.org//work/tasks/9930/13769930/Fedora-Docker-Base-23-20160423.x86_64.tar.xz}"
fi



