#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a distro-specific continuation of the prepare.sh script.

PKGEXT='rpm'
DISTROAKA='fedora'

# install_dist: see install() in prepare.sh for details.
install_dist() {
    error 1 'ERROR: install_pkg_dist is not supported on Fedora'
}


# install_pkg_dist: see install_pkg() in prepare.sh for details.
install_pkg_dist() {
    error 1 'ERROR: install_pkg_dist is not supported on Fedora'
}


# remove_dist: see remove() in prepare.sh for details.
remove_dist() {
    error 1 'ERROR: install_pkg_dist is not supported on Fedora'
}

# ensure we are in /
cd /

cat > '/etc/rc.local' <<EOF
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
#
EOF

chmod +x /etc/rc.local

umount '/var/run/lock' '/var/run'
rm -rf --one-file-system /var/run/*
