#!/bin/sh -e
# Copyright (c) 2015 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a target, but it's not selectable by the user. These are the commands
# that get executed at the very end of the generated prepare.sh.
# These commands are not optional and are automatically added to targets.

REQUIRES=''
DESCRIPTION=''
HOSTBIN='enter-chroot delete-chroot edit-chroot mount-chroot unmount-chroot'
HOSTBIN="$HOSTBIN crash_reporter_wrapper"
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

# Set the default coredump handler
if [ ! -f '/etc/crouton/core_pattern' ]; then
    core_pattern=''
    echo "\
# The first non-comment line is the core_pattern that applies to this chroot.
# See man 5 core for details.

$core_pattern" > '/etc/crouton/core_pattern'
fi

#fix dbus
mkdir /var/run/dbus
dbus-uuidgen > /etc/machine-id

mkdir /home/fedora
#fedora blue prompt:
echo 'PS1="\[\e[34;1m\][\u@\h \W]$ \[\e[0m\]"' > /home/fedora/.bash_profile

#fix permissions
chown fedora /home/fedora
chown fedora /home/fedora/.bash_profile

#dnf stuff:
echo
echo "Fedora is installed now!"
echo
echo "Getting DNF metadata and installing sudo..."
dnf install sudo -y

rm -f "$0"

cat /etc/.fedoracroutonmsg
